### ISSUE TITLE
Does not account for font-size

### ISSUE THREAD

**Issue by xiangcatherine** [mage3k/vue-autosize#10]
Hi,

It seems that the input autosize does not account for `font-size` within the input.

For example if `font-size: 200%`, the text will get cut off:

<img width="466" alt="screen shot 2017-09-12 at 9 42 05 pm" src="https://user-images.githubusercontent.com/26419914/30355740-44a31d4e-9803-11e7-9ecc-03aedbcfdd03.png">

**Comment by xiangcatherine** [comment]
Could you offer any recommendation on how to proceed? I would really like to use in my project but cannot because of this issue

**Comment by tthallos** [comment]
@xiangcatherine I already fixed it, but not update in demo page. You can install again after remove installed version in your project.

**Comment by xiangcatherine** [comment]
thanks!
